export const aboutText = `Hi! My name is Jenna Czech. I'm eighteen years old, and I'm a professional proofreader. I know I am young, but don't let my age fool you; I have taken multiple proofreading courses and I have a listing in the Self-Publishing School (SPS) Preferred Outsourcer Rolodex. I'm currently in college as well, minoring in English to potentially become an author when I graduate. Ever since I can remember, I've had hawk-eyes with anything grammar related. I've spotted all sorts of errors in magazines, menus, textbooks, and even my friend's texts. (Yes, I'm that girl ). With that said, I don't pretend to be perfect; when I proofread your work, I don't flat-out correct you. Instead, I leave comments and suggestions as to what I see needs fixing so ultimately, you are the final judge with how you'd like your work to look. (See examples of how I proofread on my "services" tab). I'd love to be the one to help you make your work look as sophisticated and professional as possible!`;

export const servicesText = `Although I have experience proofreading, I'm aware my age may deter people from wanting my services, which is why I charge only $20 an hour. If you send me your work, at a rate of just $20, I can show you how effective my work is with how much I can do for you in just an hour. 
After the hour is up, I'll send your work back to you with my proofreading comments. If you don't like how I work, you've only spent $20 on me, but if you do, we can continue working together and I'll proofread what 
you've got until I'm finished. I will try my best to work efficiently, as to not burn a whole in your wallet, but I will not rush by any means. You're trusting me to do thorough work, so I will do thorough work. Depending on how long your work is, 
it may only take me an hour to proofread. In that case, my work will be done after just $20 and you can go on your way!  I can proofread everything from manuscripts, social media/blog posts/online content, business marketing materials, etc. If there is anything you would like me to proofread that I have not listed, just shoot me an email and I'll let you know if your work is within the scope of my abilities. Note: I am willing negotiate my rates based on circumstances.`;

export const contactMeText = `I prefer to be contacted via email because I don't usually answer
phone calls from unfamiliar numbers, but if for any reason you need
to call me and I don't answer, just leave a message and I'll get
back to you as soon as I can! `;
